//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS3BackupApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS3BackupApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Steam Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountLabel_Account {
            get {
                return ResourceManager.GetString("AccountLabel_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountLabel_BackupTarget {
            get {
                return ResourceManager.GetString("AccountLabel_BackupTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complite_Backup {
            get {
                return ResourceManager.GetString("Complite_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complite_Restore {
            get {
                return ResourceManager.GetString("Complite_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All saved data stored in this profile will also be deleted.
        ///Do you want to delete the profile?
        ///
        ///Profile: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_DeleteProfile {
            get {
                return ResourceManager.GetString("Confirm_DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this saved data?
        ///
        ///Saved data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_DeleteSavedata {
            get {
                return ResourceManager.GetString("Confirm_DeleteSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override?
        ///
        ///Saved data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_Overwrite {
            get {
                return ResourceManager.GetString("Confirm_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to restore this saved data?
        ///
        ///Saved data: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm_Restore {
            get {
                return ResourceManager.GetString("Confirm_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An invalid path was specified.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentPath {
            get {
                return ResourceManager.GetString("Error_ArgumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup folder path is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BackupPathTooLong {
            get {
                return ResourceManager.GetString("Error_BackupPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the backup folder path is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BackupPathTooLongForAuto {
            get {
                return ResourceManager.GetString("Error_BackupPathTooLongForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while copying a file.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CopyEx {
            get {
                return ResourceManager.GetString("Error_CopyEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while creating the folder.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateDirectoryEx {
            get {
                return ResourceManager.GetString("Error_CreateDirectoryEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while creating the folder.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateEx {
            get {
                return ResourceManager.GetString("Error_CreateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while creating the file.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CreateFileEx {
            get {
                return ResourceManager.GetString("Error_CreateFileEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while deleting a folder.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DeleteEx {
            get {
                return ResourceManager.GetString("Error_DeleteEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory does not exist.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a backup folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyBackupPath {
            get {
                return ResourceManager.GetString("Error_EmptyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because no backup folder was selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyBackupPathForAuto {
            get {
                return ResourceManager.GetString("Error_EmptyBackupPathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select or enter a profile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptyProfile {
            get {
                return ResourceManager.GetString("Error_EmptyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a save name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_EmptySavename {
            get {
                return ResourceManager.GetString("Error_EmptySavename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while retrieving the directory.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_GetDirectoriesEx {
            get {
                return ResourceManager.GetString("Error_GetDirectoriesEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while retrieving the modification date of a folder.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_GetLastWriteTimeEx {
            get {
                return ResourceManager.GetString("Error_GetLastWriteTimeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The backup folder path specified is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPath {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the specified backup folder contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathChars {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the specified backup folder path contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathCharsForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathCharsForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the specified backup folder path is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidBackupPathForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidBackupPathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The format of the selected item is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidFormat {
            get {
                return ResourceManager.GetString("Error_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid game name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidGameName {
            get {
                return ResourceManager.GetString("Error_InvalidGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid save data folder path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePath {
            get {
                return ResourceManager.GetString("Error_InvalidSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The save data folder path contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathChars {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the save data folder path contained invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathCharsForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathCharsForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the folder path for the saved data is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSavePathForAuto {
            get {
                return ResourceManager.GetString("Error_InvalidSavePathForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O error occurred.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_IO {
            get {
                return ResourceManager.GetString("Error_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while creating the note file.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoCreateEx {
            get {
                return ResourceManager.GetString("Error_MemoCreateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while loading the note.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoReadEx {
            get {
                return ResourceManager.GetString("Error_MemoReadEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load note.
        ///Please select a backup folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoReadNoBackupPath {
            get {
                return ResourceManager.GetString("Error_MemoReadNoBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The note was not saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWrite {
            get {
                return ResourceManager.GetString("Error_MemoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The note was not saved.
        ///Please select a backup folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWriteEmptyBackupPath {
            get {
                return ResourceManager.GetString("Error_MemoWriteEmptyBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while saving the note.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MemoWriteEx {
            get {
                return ResourceManager.GetString("Error_MemoWriteEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred during renaming.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_MoveEx {
            get {
                return ResourceManager.GetString("Error_MoveEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name is already in use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Error_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the saved data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoItemSelected {
            get {
                return ResourceManager.GetString("Error_NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error: folder for saved data is not set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoSavePath {
            get {
                return ResourceManager.GetString("Error_NoSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The save data for the selected account could not be found.
        ///Please select an account again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundAccount {
            get {
                return ResourceManager.GetString("Error_NotFoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The backup folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundBackupfolder {
            get {
                return ResourceManager.GetString("Error_NotfoundBackupfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the backup folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundBackupfolderForAuto {
            get {
                return ResourceManager.GetString("Error_NotfoundBackupfolderForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundMemo {
            get {
                return ResourceManager.GetString("Error_NotFoundMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backed up save data does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotFoundSavedata {
            get {
                return ResourceManager.GetString("Error_NotFoundSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the folder to save the save data.
        ///Please start the selected game and create the save data.
        ///For REPO, please play through the single-player mode to create your save data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundSavefolder {
            get {
                return ResourceManager.GetString("Error_NotfoundSavefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic backup could not be performed because the folder where the saved data was saved could not be found.
        ///Please start the game and create the save data.
        ///For REPO, please play through the single-player mode to create your save data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotfoundSavefolderForAuto {
            get {
                return ResourceManager.GetString("Error_NotfoundSavefolderForAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported path format.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NotSupportedPath {
            get {
                return ResourceManager.GetString("Error_NotSupportedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path is too long.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_PathTooLong {
            get {
                return ResourceManager.GetString("Error_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lack of security permissions.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Security {
            get {
                return ResourceManager.GetString("Error_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while changing the modification date of a folder.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_SetLastWriteTimeEx {
            get {
                return ResourceManager.GetString("Error_SetLastWriteTimeEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have access privileges.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Error_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form_ChangeName {
            get {
                return ResourceManager.GetString("Form_ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accounts used: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Account {
            get {
                return ResourceManager.GetString("Info_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renamed from {0} to {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Rename {
            get {
                return ResourceManager.GetString("Info_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note box
        ///Select the savedata. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_SelectSavedata {
            get {
                return ResourceManager.GetString("Info_SelectSavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a new name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_EnterNewName {
            get {
                return ResourceManager.GetString("Prompt_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while saving settings.
        ///If you exit at this point, your settings may be lost.
        ///Would you like to try saving again?
        ///
        ///Error description: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning_Close {
            get {
                return ResourceManager.GetString("Warning_Close", resourceCulture);
            }
        }
    }
}
